#@TYPE: Machine
#@NAME: ECHO
#@DESCRIPTION: Machine configuration for Amboseli-RDKB
require ${COREBASE}/meta-qti-bsp/conf/machine/echo-base.conf

MACHINE_FEATURES += "dm-verity-none"

KERNEL_CONFIG_FRAGMENTS:append = " \
    ${S}/arch/arm64/configs/vendor/echo-mbb.config \
    ${S}/arch/arm64/configs/vendor/echo-rdkb.config"
KERNEL_CONFIG_FRAGMENTS:append = " ${@oe.utils.vartrue('DEBUG_BUILD', '${S}/arch/arm64/configs/vendor/echo-debug.config', '', d)}"
