# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"
BSPDIR := "${@os.path.abspath(os.path.dirname(d.getVar('FILE', True)) + '/../../..')}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "qti-qcvirtio"
BBFILE_PATTERN_qti-qcvirtio = "^${LAYERDIR}/"
BBFILE_PRIORITY_qti-qcvirtio = "10"

LAYERSERIES_COMPAT_qti-qcvirtio = "scarthgap"

LAYERDEPENDS_qti-qcvirtio = "core openembedded-layer qti-tgvm"
